apiVersion: v1
kind: Service
metadata:
    name: health-service
    namespace: auth
spec:
    selector:
        app: health-service
    ports:
        - port: 80
          targetPort: 80
    type: ClusterIP
