apiVersion: v1
kind: ConfigMap
metadata:
    name: health-config
    namespace: auth
data:
    nginx.conf: |
        server {
            listen 80;
            location /health {
                access_log off;
                return 200 '{"status":"healthy","timestamp":"2024-01-01T00:00:00Z","services":{"auth":"up","core":"up","manage":"up"}}';
                add_header Content-Type application/json;
            }
            location / {
                return 200 'ArvanCloud Microservices - Phase 5\n';
                add_header Content-Type text/plain;
            }
        }
