# activemq-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: activemq-pvc
  namespace: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
