# core-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: core
    namespace: core
spec:
    replicas: 1
    selector:
        matchLabels:
            app: core
    template:
        metadata:
            labels:
                app: core
        spec:
            containers:
                - name: core
                  image: project-core-service
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8080
                  envFrom:
                      - configMapRef:
                            name: core-config

                  env:
                      - name: PROJECT_DATASOURCE_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: core-db-credentials
                                key: DB_USER
                      - name: PROJECT_DATASOURCE_PASS
                        valueFrom:
                            secretKeyRef:
                                name: core-db-credentials
                                key: DB_PASS

                      - name: ACTIVEMQ_KEY
                        valueFrom:
                            secretKeyRef:
                                name: core-activemq-credentials
                                key: ACTIVEMQ_KEY
                      - name: ACTIVEMQ_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: core-activemq-credentials
                                key: ACTIVEMQ_PASS
                      - name: ACTIVEMQ_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: core-activemq-credentials
                                key: ACTIVEMQ_USER

                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                      limits:
                          memory: "500Mi"
                          cpu: "500m"
