# core-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: core
    namespace: core
spec:
    replicas: 2
    selector:
        matchLabels:
            app: core
    template:
        metadata:
            labels:
                app: core
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: node-role.kubernetes.io/cloud-container-g2
                                    operator: In
                                    values:
                                        - "true"
                                  - key: topology.kubernetes.io/zone
                                    operator: In
                                    values:
                                        # - bamdad
                                        - simin
                                        # - foough
                # podAntiAffinity:
                #     requiredDuringSchedulingIgnoredDuringExecution:
                #         - labelSelector:
                #               matchLabels:
                #                   app: core
                #           topologyKey: topology.kubernetes.io/zone
            containers:
                - name: core
                  image: saeedsomething/project-core-service:latest
                  imagePullPolicy: Always
                  securityContext:
                      privileged: false
                  ports:
                      - containerPort: 8080
                  envFrom:
                      - configMapRef:
                            name: core-config
                  env:
                      - name: PROJECT_DATASOURCE_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: core-db-credentials
                                key: DB_USER
                      - name: PROJECT_DATASOURCE_PASS
                        valueFrom:
                            secretKeyRef:
                                name: core-db-credentials
                                key: DB_PASS

                      - name: ACTIVEMQ_KEY
                        valueFrom:
                            secretKeyRef:
                                name: core-activemq-credentials
                                key: ACTIVEMQ_KEY
                      - name: ACTIVEMQ_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: core-activemq-credentials
                                key: ACTIVEMQ_PASS
                      - name: ACTIVEMQ_USERNAME
                        valueFrom:
                            secretKeyRef:
                                name: core-activemq-credentials
                                key: ACTIVEMQ_USER
                      - name: JAVA_TOOL_OPTIONS
                        value: "-XX:-UseContainerSupport -Djdk.disable.cgroup=true -Dcom.sun.management.jmxremote=false"

                  resources:
                      requests:
                          memory: 2Gi
                          cpu: "1.0"
                      limits:
                          memory: 2Gi
                          cpu: "1.0"
