# core-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: core-config
    namespace: core
data:
    # JDBC URL points at the internal Postgres Service
    PROJECT_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/core_db"
    PROJECT_DATASOURCE_SCHEMA: "core_db"
    # ActiveMQ broker address (cluster-internal)
    PROJECT_ACTIVEMQ_BROKER_URL: "tcp://activemq:61616"
    # Auth service endpoints
    AUTH_SERVICE_BASE_URL: "http://auth-http.auth.svc.cluster.local:8082"
    AUTH_GRPC_ADDRESS: "auth-grpc.auth.svc.cluster.local"
    AUTH_GRPC_PORT: "50051"
    PORT: ":8082"
    SPRING_DATASOURCE_SCHEMA: "public"
    ACTIVEMQ_URL: "failover:(tcp://activemq:61616)?randomize=true&jms.useAsyncSend=true&jms.sendTimeout=5000"
    ACTIVEMQ_USERNAME: "admin"
    PROJECT_URL_CONFIG: "http://localhost:30080"
    PROJECT_SPRING_DATASOURCE_HIKARI_CONNECTIONTIMEOUT: "300000" # e.g., 10 seconds
