apiVersion: v1
kind: Secret
metadata:
  name: core-db-credentials
  namespace: core
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASS: postgres  # PostgreSQL container environment variables (plain text, not base64)
  username64: postgres
  # Plain text password for PostgreSQL
  password64: postgres