apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    namespace: core
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:13.13-bullseye
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: core-db-credentials
                                key: username64
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: core-db-credentials
                                key: password64
                      - name: POSTGRES_DB
                        value: "core_db"
                  resources:
                      requests:
                          memory: "256Mi"
                          cpu: "250m"
                      limits:
                          memory: "512Mi"
                          cpu: "500m"
                  volumeMounts:
                      - name: postgres-storage
                        mountPath: /var/lib/postgresql/data
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                      claimName: postgres-pvc
