apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-lb
    namespace: nginx-lb
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nginx-lb
    template:
        metadata:
            labels:
                app: nginx-lb
        spec:
            containers:
                - name: nginx
                  image: nginx:1.21
                  ports:
                      - containerPort: 80
                  volumeMounts:
                      - name: nginx-config
                        mountPath: /etc/nginx/nginx.conf
                        subPath: nginx.conf
                  resources:
                      requests:
                          cpu: 100m
                          memory: 128Mi
                      limits:
                          cpu: 200m
                          memory: 256Mi
            volumes:
                - name: nginx-config
                  configMap:
                      name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-lb-service
    namespace: nginx-lb
spec:
    selector:
        app: nginx-lb
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30080
    type: NodePort
