apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-lb
    namespace: ingress-nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx-lb
    template:
        metadata:
            labels:
                app: nginx-lb
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: node-role.kubernetes.io/cloud-container-g2
                                    operator: In
                                    values:
                                        - "true"
                                  - key: topology.kubernetes.io/zone
                                    operator: In
                                    values:
                                        # - bamdad
                                        # - simin
                                        - forough
                # podAntiAffinity:
                #     requiredDuringSchedulingIgnoredDuringExecution:
                #         - labelSelector:
                #               matchLabels:
                #                   app: nginx-lb
                #           topologyKey: topology.kubernetes.io/zone
            containers:
                - name: nginx
                  image: nginx:1.21
                  ports:
                      - containerPort: 80
                  volumeMounts:
                      - name: nginx-config
                        mountPath: /etc/nginx/nginx.conf
                        subPath: nginx.conf
                  #   resources:
                  resources:
                      requests:
                          cpu: "0.5"
                          memory: 1Gi
                      limits:
                          cpu: "0.5"
                          memory: 1Gi
            volumes:
                - name: nginx-config
                  configMap:
                      name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-lb-service
    namespace: ingress-nginx
spec:
    selector:
        app: nginx-lb
    ports:
        - port: 80
          targetPort: 80
    type: ClusterIP
