apiVersion: v1
kind: Service
metadata:
  name: auth-nodeport
  namespace: auth
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
      name: http