# mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
    namespace: auth
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: node-role.kubernetes.io/cloud-container-g2
                                    operator: In
                                    values:
                                        - "true"
                                  - key: topology.kubernetes.io/zone
                                    operator: In
                                    values:
                                        - bamdad
                                        # - simin
                                        # - foough
                # podAntiAffinity:
                #     requiredDuringSchedulingIgnoredDuringExecution:
                #         - labelSelector:
                #               matchLabels:
                #                   app: mysql
                #           topologyKey: topology.kubernetes.io/zone
            containers:
                - name: mysql
                  image: mysql:latest
                  env:
                      - name: MYSQL_DATABASE
                        value: "authdb"
                      - name: MYSQL_USER
                        valueFrom:
                            secretKeyRef:
                                name: auth-db-credentials
                                key: DB_USER
                      - name: MYSQL_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: auth-db-credentials
                                key: DB_PASSWORD
                      - name: MYSQL_ROOT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: auth-db-credentials
                                key: DB_PASSWORD
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                      - name: mysql-data
                        mountPath: /var/lib/mysql
                  resources:
                      requests:
                          cpu: 1
                          memory: 1Gi
                      limits:
                          cpu: 2
                          memory: 2Gi
            volumes:
                - name: mysql-data
                  persistentVolumeClaim:
                      claimName: mysql-pvc
