apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: microservices-ingress
    namespace: auth
    annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
    rules:
        - http:
              paths:
                  # Auth service routes (including manage service in auth namespace)
                  - path: /auth(/|$)(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: auth-http
                            port:
                                number: 8082
                  # Manage service routes (in auth namespace)
                  - path: /manage(/|$)(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: manage
                            port:
                                number: 8080
                  # Core service routes
                  - path: /core(/|$)(.*)
                    pathType: Prefix
                    backend:
                        service:
                            name: core
                            port:
                                number: 8080
                  # Health check endpoint
                  - path: /health
                    pathType: Exact
                    backend:
                        service:
                            name: health-service
                            port:
                                number: 80
