kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
    - role: control-plane # master 1
      image: docker.arvancloud.ir/kindest/node:v1.32.2
      extraPortMappings:
          - containerPort: 6443
            hostPort: 30443
            protocol: TCP
          - containerPort: 30080 # Nginx service
            hostPort: 30080
            protocol: TCP
    - role: control-plane # master 2
      image: docker.arvancloud.ir/kindest/node:v1.32.2
      extraPortMappings:
          - containerPort: 6443
            hostPort: 30444
            protocol: TCP
    - role: worker
      image: docker.arvancloud.ir/kindest/node:v1.32.2
    - role: worker
      image: docker.arvancloud.ir/kindest/node:v1.32.2

networking:
    disableDefaultCNI: false
