apiVersion: apps/v1
kind: Deployment
metadata:
    name: manage
    namespace: auth
spec:
    replicas: 1
    selector:
        matchLabels:
            app: manage
    template:
        metadata:
            labels:
                app: manage
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: node-role.kubernetes.io/cloud-container-g2
                                    operator: In
                                    values:
                                        - "true"
                                  - key: topology.kubernetes.io/zone
                                    operator: In
                                    values:
                                        - bamdad
                                        # - simin
                                        # - foough
                # podAntiAffinity:
                #     requiredDuringSchedulingIgnoredDuringExecution:
                #         - labelSelector:
                #               matchLabels:
                #                   app: auth
                #           topologyKey: topology.kubernetes.io/zone
            containers:
                - name: manage
                  image: saeedsomething/project-manage-service:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                  env:
                      # non-sensitive
                      - name: DB_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: manage-configmap
                                key: DB_HOST
                      - name: DB_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: manage-configmap
                                key: DB_PORT
                      - name: DB_USER
                        valueFrom:
                            configMapKeyRef:
                                name: manage-configmap
                                key: DB_USER
                      - name: DB_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                name: manage-configmap
                                key: DB_PASSWORD
                      - name: DB_NAME
                        valueFrom:
                            configMapKeyRef:
                                name: manage-configmap
                                key: DB_NAME
                      - name: SERVER_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: manage-configmap
                                key: SERVER_PORT
