apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: core-hpa
    namespace: core
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: core
    minReplicas: 2
    maxReplicas: 8
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 30
        # - type: Resource
        #   resource:
        #       name: memory
        #       target:
        #           type: Utilization
        #           averageUtilization: 60
    behavior:
        scaleDown:
            stabilizationWindowSeconds: 0
            policies:
                - type: Pods
                  value: 1
                  periodSeconds: 10
                - type: Percent
                  value: 50
                  periodSeconds: 10
        scaleUp:
            stabilizationWindowSeconds: 15
            policies:
                - type: Pods
                  value: 1
                  periodSeconds: 15
                - type: Percent
                  value: 50
                  periodSeconds: 15
