apiVersion: batch/v1
kind: CronJob
metadata:
    name: auth-db-backup
    namespace: auth
spec:
    schedule: "0 2 * * *" # Daily at 2 AM
    jobTemplate:
        spec:
            template:
                spec:
                    affinity:
                        nodeAffinity:
                            preferredDuringSchedulingIgnoredDuringExecution:
                                - weight: 100
                                  preference:
                                      matchExpressions:
                                          - key: topology.kubernetes.io/zone
                                            operator: In
                                            values:
                                                - bamdad # Same zone as MySQL
                    containers:
                        - name: mysql-backup
                          image: mysql:8.0
                          command:
                              - /bin/bash
                              - -c
                              - |
                                  echo "Starting backup at $(date)"
                                  mysqldump -h mysql -u root -p$MYSQL_ROOT_PASSWORD --single-transaction --routines --triggers authdb > /backup/auth-db-$(date +%Y%m%d-%H%M%S).sql
                                  echo "Backup completed at $(date). File: auth-db-$(date +%Y%m%d-%H%M%S).sql"
                                  ls -la /backup/
                          env:
                              - name: MYSQL_ROOT_PASSWORD
                                valueFrom:
                                    secretKeyRef:
                                        name: auth-db-credentials
                                        key: DB_PASSWORD
                          volumeMounts:
                              - name: backup-storage
                                mountPath: /backup
                          resources:
                              requests:
                                  cpu: 1
                                  memory: 512Mi
                              limits:
                                  cpu: 1
                                  memory: 1Gi
                    volumes:
                        - name: backup-storage
                          persistentVolumeClaim:
                              claimName: auth-db-backup-pvc
                    restartPolicy: OnFailure
