apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: auth-db-backup-pvc
    namespace: auth
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: arvancloud-backup
