apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: arvancloud-backup
provisioner: kubernetes.io/no-provisioner
parameters:
    type: ssd
    replication-type: replica-3
    backup-enabled: "true"
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
